import { PartialType } from '@nestjs/mapped-types';
import { IsIn, IsISO8601, IsOptional, IsString, MaxLength } from 'class-validator';

/** Event types that users can record by hand; the rest are generated by the server. */
export const MANUAL_EVENT_TYPES = ['note', 'interview', 'follow_up'] as const;
export type ManualEventType = (typeof MANUAL_EVENT_TYPES)[number];

export class CreateJobEventDto {
  @IsIn(MANUAL_EVENT_TYPES)
  type!: ManualEventType;

  @IsOptional()
  @IsString()
  @MaxLength(300)
  title?: string | null;

  @IsOptional()
  @IsString()
  @MaxLength(20_000)
  body?: string | null;

  @IsOptional()
  @IsISO8601()
  occurredAt?: string;
}

export class UpdateJobEventDto extends PartialType(CreateJobEventDto) {}
