import { Download, GanttChart } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useTimeline } from '../api/hooks';
import { PageHeader } from '../components/PageHeader';
import { Button, ButtonLink } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Alert, EmptyState, errorText } from '../components/ui/feedback';
import { Checkbox } from '../components/ui/fields';
import { PageSpinner } from '../components/ui/Spinner';
import {
  buildGanttRows,
  downloadPng,
  downloadSvg,
  GANTT_THEMES,
  renderGanttSvg,
} from '../lib/gantt';
import { todayIso } from '../lib/format';

export function TimelinePage() {
  const [archived, setArchived] = useState(false);
  const [darkExport, setDarkExport] = useState(() =>
    document.documentElement.classList.contains('dark'),
  );
  const [exportError, setExportError] = useState<string>();
  const { data: jobs, isPending, error } = useTimeline(archived);

  const svg = useMemo(
    () =>
      jobs ? renderGanttSvg(buildGanttRows(jobs), GANTT_THEMES[darkExport ? 'dark' : 'light']) : '',
    [jobs, darkExport],
  );
  const filename = `jobify-timeline-${todayIso()}`;

  const save = async (format: 'png' | 'svg') => {
    setExportError(undefined);
    try {
      if (format === 'svg') downloadSvg(svg, `${filename}.svg`);
      else await downloadPng(svg, `${filename}.png`);
    } catch (cause) {
      setExportError(errorText(cause));
    }
  };

  return (
    <>
      <PageHeader
        title="Timeline"
        description="Every application as a bar, coloured by status, with interviews marked. Save it as an image to share or print."
        actions={
          <>
            <Button
              icon={<Download className="size-4" />}
              onClick={() => save('png')}
              disabled={!jobs?.length}
            >
              Save PNG
            </Button>
            <Button
              icon={<Download className="size-4" />}
              onClick={() => save('svg')}
              disabled={!jobs?.length}
            >
              Save SVG
            </Button>
          </>
        }
      />

      <div className="mb-4 flex flex-wrap items-center gap-4">
        <Checkbox
          label="Archived jobs"
          checked={archived}
          onChange={(event) => setArchived(event.target.checked)}
        />
        <Checkbox
          label="Dark background"
          checked={darkExport}
          onChange={(event) => setDarkExport(event.target.checked)}
        />
      </div>
      {exportError && <Alert className="mb-4">{exportError}</Alert>}

      <Card className="overflow-hidden">
        {isPending ? (
          <PageSpinner />
        ) : error ? (
          <div className="p-5">
            <Alert>{errorText(error)}</Alert>
          </div>
        ) : jobs.length === 0 ? (
          <EmptyState
            icon={<GanttChart className="size-6" />}
            title="Nothing to chart yet"
            description={archived ? 'No archived jobs.' : 'Add a job and it will appear here.'}
            action={!archived && <ButtonLink to="/jobs/new">Add job</ButtonLink>}
          />
        ) : (
          // The SVG is generated by Jobify from job titles and companies, which it escapes.
          <div className="overflow-x-auto" dangerouslySetInnerHTML={{ __html: svg }} />
        )}
      </Card>
    </>
  );
}
